language: ruby
matrix:
  include:
    - rvm: jruby-9k
      jdk: oraclejdk7
      before-install: gem install bundler --no-ri --no-rdoc
    - rvm: jruby-9k
      jdk: oraclejdk8
      before-install: gem install bundler --no-ri --no-rdoc
    - rvm: jruby-9k
      jdk: openjdk7
      before-install: gem install bundler --no-ri --no-rdoc

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname
