name: Ruby Build
on:
  push:
    branches: master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'contrib/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'contrib/**'

jobs:
  jruby_build:
    name: JRuby (${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [jruby-9.4]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
      - name: Create WAR executable
        run: bundle exec warble runnable war ${{ github.workspace }}/Gemfile

  mri_build:
    name: Ruby (${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2.1', '3.3', '3.4']
    steps:
      - name: Install required system dependencies
        run: |
          sudo apt-get install -y libyaml-dev
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: 3.5.14
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake

  selenium:
    name: Selenium on MRI
    runs-on: ubuntu-latest
    steps:
      - name: Install required system dependencies
        run: |
          sudo apt-get install -y libyaml-dev
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install Chromedriver
        uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test:capybara
